runtime:
  profile: sit
  configServerUrl: http://config-server:8888

auth:
  secrets:
    enabled: true

kafka:
  bootstrapServers: kafka.digital-bank-sit.svc.cluster.local:9092
  securityProtocol: PLAINTEXT

reservationEvents:
  enabled: true
  sitPlaintextEnabled: true

ledgerEvents:
  enabled: true
  sitPlaintextEnabled: true

mfaAssuranceEvents:
  enabled: true
  sitPlaintextEnabled: true
  bootstrapServers: kafka.digital-bank-sit.svc.cluster.local:9092
  securityProtocol: PLAINTEXT
